spring:
  application:
    name: accounts-service  # Identify this application

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Application info
info:
  app:
    name: Microservices Demo - Accounts Server
    description: This is a RESTful web service
    version: 1.0.0
